### ISSUE TITLE
Reporte 

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/practica-architect-christopheremv#1]
[PRACTICA ARCHITECT.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-christopheremv/files/7151739/PRACTICA.ARCHITECT.pdf)

**Comment by IsraelNicolas61** [comment]
¡Buen trabajo!
Calificación 18/20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
